/* CRIANDO UM BANCO DE DADOS */

CREATE DATABASE TIME;

/* CONECTANDO AO BANCO DE DADOS*/

USE TIME

/* CRIANDO TABELA JOGADORES */

CREATE TABLE JOGADORES(
	ID_JOGADOR INT UNIQUE AUTO_INCREMENT,
	NOME VARCHAR(20),
	SOBRENOME VARCHAR(20),
	NASCIMENTO DATE
);

/* CRIANDO TABELA LOCALIZACAO */

CREATE TABLE LOCALIZACAO(
	ID_CIDADE INT UNIQUE AUTO_INCREMENT,
	CIDADE VARCHAR(20),
	ESTADO VARCHAR(20),
	UF CHAR(2),
	IdJOGADOR INT
);

/* INSERINDO CHAVE PRIMARIA NA TABELA JOGADOR */

ALTER TABLE JOGADORES
ADD CONSTRAINT PK_JOGADOR
PRIMARY KEY (ID_JOGADOR);

/* DESCRIÇÃO DA TABELA JOGADORES */ 

SHOW CREATE TABLE JOGADORES;

/* INSERINDO CHAVE ESTRAGEIRA NA TABELA LOCALIZACAO */

ALTER TABLE LOCALIZACAO
ADD CONSTRAINT FK_JOGADORES_LOCALIZACAO
FOREIGN  KEY (IdJOGADOR)
REFERENCES JOGADORES(ID_JOGADOR);

/* DESCRIÇÃO DA TABELA LOCALIZAÇÃO */

SHOW CREATE TABLE LOCALIZACAO;

/* INSERINDO VALORES DA TABELA JOGADORES */

INSERT INTO JOGADORES VALUES(NULL,"Neymar","da Silva","1992/02/05"),
							(NULL,"Carlos","Casimiro","1992/02/23"),
							(NULL,"Edson","Arantes","1940/10/23"),
							(NULL,"Ronaldo","de Assis","1980/03/21"),
							(NULL,"Ronaldo Luís","Nazário","1976/09/22"),
							(NULL,"Robson","de Souza","1984/01/25"),
							(NULL,"Alexandre","Pato","1989/10/02");
							
							
/* INSERINDO VALORES DA TAELA LOCALIZACAO */

INSERT INTO LOCALIZACAO VALUES(NULL,"MOGI DAS CRUZES","SAO PAULO","SP",1),
							(NULL,"SAO JOSE DOS CAMPOS","SAO PAULO","SP",2),
							(NULL,"TRES CORACOES","MINAS GERAIS","MG",3),
							(NULL,"PORTO ALEGRE","RIO GRANDE DO SUL","RS",4),
							(NULL,"RIO DE JANEIRO","RIO DE JANEIRO","RJ",5),
							(NULL,"SAO VICENTE","SAO PAULO","SP",6),
							(NULL,"PATO BRANCO","PARANA","PR",7);
							
/* TRAZENDO NOME, SOBRENOME E ESTADO */

SELECT J.NOME,J.SOBRENOME, L.ESTADO
FROM JOGADORES J
INNER JOIN LOCALIZACAO L
ON L.IdJOGADOR = J.ID_JOGADOR

/* INSERINDO UM DADO NA TABELA COM A DATA INCORRETA */

INSERT INTO JOGADORES VALUES(NULL,"Rivaldo Vítor","Borba Ferreira","1980/04/19")

/* CORRIGINDO O DADO INSERIDO INCORRETAMENTE */

UPDATE JOGADORES
SET NASCIMENTO = "1972/04/19"
WHERE ID_JOGADOR = 1;


/* DELETANDO UMA LINHA COM DADOS */

DELETE FROM JOGADORES
WHERE ID_JOGADOR = 8;


							
							